# Generated by Django 5.2.6 on 2025-12-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251211_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'مواطن'), ('organization', 'منظمة'), ('contractor', 'متعهد'), ('system_admin', 'مدير النظام')], default='citizen', max_length=20),
        ),
    ]
