# Generated by Django 5.2.6 on 2026-01-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=963, max_length=15),
            preserve_default=False,
        ),
    ]
