# Generated by Django 5.2.6 on 2025-12-16 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_delete_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المشروع')),
                ('project_type', models.CharField(choices=[('comprehensive', 'إعادة الإعمار الشاملة'), ('community', 'الدعم المجتمعي'), ('development', 'التنمية الإنشائية الجديدة')], max_length=50, verbose_name='نوع المشروع')),
                ('description', models.TextField(verbose_name='وصف تفصيلي عن المشروع')),
                ('damage_type', models.CharField(choices=[('total', 'كلي'), ('partial', 'جزئي')], max_length=50, verbose_name='نوع الضرر')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('governorate', models.CharField(choices=[('damascus', 'دمشق'), ('aleppo', 'حلب'), ('homs', 'حمص'), ('hama', 'حماة'), ('latakia', 'اللاذقية'), ('tartus', 'طرطوس'), ('daraa', 'درعا'), ('as_suwayda', 'السويداء'), ('raqqa', 'الرقة'), ('deir_ez_zor', 'دير الزور'), ('hasakah', 'الحسكة'), ('idlib', 'إدلب'), ('rural_damascus', 'ريف دمشق')], max_length=50, verbose_name='المحافظة')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('image1', models.ImageField(upload_to='project_images/', verbose_name='الصورة الأولى')),
                ('image2', models.ImageField(upload_to='project_images/', verbose_name='الصورة الثانية')),
                ('image3', models.ImageField(upload_to='project_images/', verbose_name='الصورة الثالثة')),
                ('image4', models.ImageField(upload_to='project_images/', verbose_name='الصورة الرابعة')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='التكلفة المقدرة')),
                ('duration', models.IntegerField(default=0, verbose_name='المدة المقدرة (بالأيام)')),
                ('priority_score', models.IntegerField(default=0, verbose_name='درجة الأولوية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20, verbose_name='حالة المشروع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
    ]
