# Generated by Django 5.2.6 on 2025-12-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='المساحة (م²)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='المدة المقدرة (بالأيام)'),
        ),
    ]
