# Generated by Django 5.2.6 on 2025-12-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_area_alter_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='بالدولار الأمريكي (USD)', max_digits=15, verbose_name='التكلفة المقدرة'),
        ),
    ]
