# Generated by Django 5.2.6 on 2025-12-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_estimated_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='damage_type',
            field=models.CharField(choices=[('partial', 'جزئي')], max_length=50, verbose_name='نوع الضرر'),
        ),
    ]
