# Generated by Django 5.2.6 on 2025-12-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_damage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='ملغى نهائياً'),
        ),
    ]
