# Generated by Django 5.2.6 on 2025-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_is_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_cost',
            field=models.IntegerField(help_text='بالدولار الأمريكي (USD)', verbose_name='التكلفة المقدرة'),
        ),
    ]
