# Generated by Django 5.2.6 on 2025-12-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_estimated_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('total', 'كلي'), ('partial', 'جزئي')], max_length=50, null=True, verbose_name='نوع الضرر'),
        ),
    ]
