# Generated by Django 5.2.6 on 2025-12-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
